---
Name: imagesliderconfig
---
SiteTree:
  extensions:
    - ImageSliderPageExtension

Page_Controller:
  extensions:
    - ImageSliderControllerInit

SiteConfig:
  extensions:
    - ImageSliderSiteConfigExtension

ImageSliderConfig:
  PageTypeExcludes:
    - 'VirtualPage'
    - 'ErrorPage'
    - 'RedirectorPage'
    - 'BlogTree'
    - 'BlogEntry'
    - 'BlogHolder'