---
Name: imagesliderconfig
---
SiteTree:
  extensions:
    - ImageSliderPageExtension

Page_Controller:
  extensions:
    - ImageSliderControllerInit

SiteConfig:
  extensions:
    - ImageSliderSiteConfigExtension